CREATE TABLE CLIENTE(
	IDCLIENTE		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	CPF				NVARCHAR(11)		NOT NULL UNIQUE,
	PRIMARY KEY(IDCLIENTE))
GO

CREATE TABLE PRODUTO(
	IDPRODUTO		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	PRECO			DECIMAL(18,2)		NOT NULL,
	PRIMARY KEY(IDPRODUTO))
GO

CREATE TABLE PEDIDO(
	IDPEDIDO		UNIQUEIDENTIFIER	NOT NULL,
	IDCLIENTE		UNIQUEIDENTIFIER	NOT NULL,
	DATAPEDIDO		DATE				NOT NULL,
	PRIMARY KEY(IDPEDIDO),
	FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE))
GO

CREATE TABLE ITEMPEDIDO(
	IDITEMPEDIDO	UNIQUEIDENTIFIER	NOT NULL,
	IDPEDIDO		UNIQUEIDENTIFIER	NOT NULL,
	IDPRODUTO		UNIQUEIDENTIFIER	NOT NULL,
	QUANTIDADE		INTEGER				NOT NULL,
	PRIMARY KEY(IDITEMPEDIDO),
	FOREIGN KEY(IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO),
	FOREIGN KEY(IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO))
GO


